[package]
name = "label_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "label_sum"

[dependencies]
num = { version = "0.4"}
rand = "0.8.5"
json = "0.12.4"
